"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from burger_sdk.types import BaseModel
from burger_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteBurgerRequestTypedDict(TypedDict):
    burger_id: int


class DeleteBurgerRequest(BaseModel):
    burger_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
