"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from burger_sdk.types import BaseModel
from datetime import datetime
from enum import Enum
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OrderStatus(str, Enum):
    r"""Status of the order"""

    CREATED = "CREATED"
    PREPARING = "PREPARING"
    READY = "READY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class OrderOutputTypedDict(TypedDict):
    r"""An order to be returned"""

    burger_ids: List[int]
    r"""List of burger ids in the order"""
    id: int
    r"""The id of the order"""
    status: OrderStatus
    table: int
    r"""Table number for the order"""
    time: datetime
    r"""Time of the order"""
    note: NotRequired[str]
    r"""Note for the order"""


class OrderOutput(BaseModel):
    r"""An order to be returned"""

    burger_ids: List[int]
    r"""List of burger ids in the order"""

    id: int
    r"""The id of the order"""

    status: OrderStatus

    table: int
    r"""Table number for the order"""

    time: datetime
    r"""Time of the order"""

    note: Optional[str] = None
    r"""Note for the order"""
